---
- name: install apache
  yum: 
   name: httpd

- name: start httpd
  systemd:
    name: httpd
    enabled: yes
    state: started

- name: register epel
  yum:
    name: epel-release

- name: register remi
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

- name: install php7.1
  yum: 
    enablerepo: remi-php71
    name: "{{ item }}"
  with_items: 
    - php
    # - php-devel
    # - php-pear
    # - php-mbstring
    # - php-mysql

- name: create yum repository file (MariaDB10.2)
  copy:
    src: MariaDB.repo
    dest: /etc/yum.repos.d/MariaDB.repo
    mode: 0644

- name: install MariaDB10.2
  yum:
    name: "{{ item }}"
  with_items: 
    - MariaDB-server
    - MariaDB-client

- name: start mysql
  systemd:
    name: mariadb
    enabled: yes
    state: started

- name: install MySQL-python for mysql_user module
  yum:
    name: MySQL-python

- name: setting MySQL user
  mysql_user:
    name: "{{ mysql.root.user}}"
    password: "{{ mysql.root.password }}"

- name: install phpMyAdmin
  yum:
    enablerepo: remi,remi-php71
    name: phpMyAdmin

- name: setting phpMyAdmin (Apache2.4)
  replace:
    dest: /etc/httpd/conf.d/phpMyAdmin.conf
    regexp: "Require local"
    replace: "Require all granted"
  notify: 
    - restart httpd
